baseURL: 'https://rycko.online/'
theme: 'up-business-theme'
languageCode: 'en-us'

title: 'Programación web'

googleAnalytics: 'G-65S3XZGWSZ'

summaryLength: 20

params:
  title: 'Programación web'
  description: 'Proveedor de servicios de programación web, maquetación web, reparación y mejoramiento de sitios web, los mantenemos y los administramos por ti.'
  images:
    - 'images/hero-image.png'

  logo: 'arrow-up.png'

  favicons:
    themeColor: '#FFFFFF'
    backgroundColor: '#FFFFFF'
    faviconColor: '#000000'

  social:
    tiktok: '#'
    instagram: '#'
    facebook: '#'
    youtube: '#'

  location:
    - 'Colonia centro, Orizaba, Veracruz.'

  contact:
    - 'negociosrentablesdigitales@gmail.com'
    - '272 143 2867'

  copyright: '© 2022 Servicios de programación web'

menus:
  main:
    - name: 'Inicio'
      url: '/'
      weight: 1

    - name: 'Como trabajamos'
      url: '/Como-trabajamos'
      weight: 2

    - name: 'Quienes somos'
      url: '/about'
      weight: 3

    - name: 'Precios'
      url: '/prices'
      weight: 4

    - name: 'Blog'
      url: '/posts'
      weight: 5

  buttons:
    - name: 'Consulta gratuita'
      url: 'https://bit.ly/3VJy43S'
      weight: 5
      pre: 'btn btn-primary text-light'

  footer:
    - name: 'Términos y condiciones'
      url: '/terminos-y-condiciones'
      weight: 1

    - name: 'Políticas de privacidad'
      url: '/politicas-de-privacidad'
      weight: 2

taxonomies:
  tags: 'tags'
