baseURL: 'https://rycko.online/'
theme: 'up-business-theme'
languageCode: 'en-us'

title: 'Rycko'

googleAnalytics: 'G-65S3XZGWSZ'

summaryLength: 20

params:
  title: 'Rycko Programación web y Marketing Digital'
  description: 'Somos una empresa líder en diseño y desarrollo de páginas web, especializada en marketing digital, comunicación y branding. Ofrecemos servicios de diseño web personalizado, asesoramiento en marketing digital, estrategias de comunicación efectiva y construcción de identidad de marca. Nuestro objetivo es mejorar la presencia en línea de nuestros clientes y ayudarles a alcanzar el éxito en el mundo digital. Contáctenos hoy mismo para descubrir cómo podemos ayudarlo a lograr sus objetivos y hacer crecer su negocio en línea.'
  images:
    - 'images/hero-image.png'

  logo: 'arrow-up.png'

  favicons:
    themeColor: '#FFFFFF'
    backgroundColor: '#FFFFFF'
    faviconColor: '#000000'

  social:
    tiktok: 'https://www.tiktok.com/@rycko.online'
    instagram: 'https://www.instagram.com/rycko.online/'
    facebook: 'https://www.facebook.com/ryckofreelance'
    youtube: '#'

  location:
    - 'Colonia centro, Orizaba, Veracruz.'

  contact:
    - 'negociosrentablesdigitales@gmail.com'
    - '272 143 2867'

  copyright: '© 2023 rycko.online servicios de programación web y '

menus:
  main:
    - name: 'Inicio'
      url: '/'
      weight: 1

    - name: 'Como trabajamos'
      url: '/Como-trabajamos'
      weight: 2

    - name: 'Quienes somos'
      url: '/about'
      weight: 3

    - name: 'Blog'
      url: '/posts'
      weight: 4

  buttons:
    - name: 'Consulta gratuita'
      url: 'https://bit.ly/3VJy43S'
      weight: 5
      pre: 'btn btn-primary text-light'

  footer:
    - name: 'Términos y condiciones'
      url: '/terminos-y-condiciones'
      weight: 1

    - name: 'Políticas de privacidad'
      url: '/politicas-de-privacidad'
      weight: 2

taxonomies:
  tags: 'tags'
